apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
spec:
  type: {{ .Values.service.type }} # clusterIP means  Service is completely isolated from the outside world.
  selector:
    app: {{ .Values.app.name }}    
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
